name: asklora_flutter_test
description: Flutter project as the skeleton for Flutter recruitment test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  web_socket_channel: ^2.1.0
  timeago: ^3.2.2
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/token_icon/
    - assets/dashboard/
    - assets/
